// <auto-generated />
using System;
using GoogDocsLite.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoogDocsLite.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260225163719_Stage45SharingAndLocks")]
    partial class Stage45SharingAndLocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("GoogDocsLite.Server.Data.Entities.DocumentEditLockEntity", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastHeartbeatAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LockOwnerDisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LockOwnerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DocumentId");

                    b.ToTable("DocumentEditLocks", (string)null);
                });

            modelBuilder.Entity("GoogDocsLite.Server.Data.Entities.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId", "UpdatedAt");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("GoogDocsLite.Server.Data.Entities.DocumentInviteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteeEmailNormalized")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("InviteeEmailNormalized", "Status");

                    b.ToTable("DocumentInvites", (string)null);
                });

            modelBuilder.Entity("GoogDocsLite.Server.Data.Entities.DocumentPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrantedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "UserId")
                        .IsUnique();

                    b.ToTable("DocumentPermissions", (string)null);
                });

            modelBuilder.Entity("GoogDocsLite.Server.Data.Entities.DocumentEditLockEntity", b =>
                {
                    b.HasOne("GoogDocsLite.Server.Data.Entities.DocumentEntity", "Document")
                        .WithOne("EditLock")
                        .HasForeignKey("GoogDocsLite.Server.Data.Entities.DocumentEditLockEntity", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("GoogDocsLite.Server.Data.Entities.DocumentInviteEntity", b =>
                {
                    b.HasOne("GoogDocsLite.Server.Data.Entities.DocumentEntity", "Document")
                        .WithMany("Invites")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("GoogDocsLite.Server.Data.Entities.DocumentPermissionEntity", b =>
                {
                    b.HasOne("GoogDocsLite.Server.Data.Entities.DocumentEntity", "Document")
                        .WithMany("Permissions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("GoogDocsLite.Server.Data.Entities.DocumentEntity", b =>
                {
                    b.Navigation("EditLock");

                    b.Navigation("Invites");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
